// Autogenerated using the moz templater annotation.
//
//
package dimo

import "time"

var (
	// defaultSendWithBeforeAbort defines the time to await receiving a message else aborting.
	defaultSendWithBeforeAbort = 3 * time.Second
)
